Add Mono/Unity support and extend constraints support
BrannonKing/NLoptNet pull request #19
Opened 2021-07-02 09:04 UTC by JeremyBois

- Add mono and Unity3d support
  - Add support for both
    - nlopt_add_equality_mconstraint 
    - nlopt_add_inequality_mconstraint

2021-07-28 14:09 UTC, BrannonKing requested changes
Do we need to upgrade the deployment frameworks to include Mono somehow?

2021-07-28 14:09 UTC, BrannonKing commented on NLoptNet/NLoptSolver.cs
> +                    IntPtr p_x,
Why not use the MONO approach for all frameworks? Is there any performance difference with the MarshalAs approach?

2021-07-28 14:09 UTC, BrannonKing commented on NLoptNet/NLoptSolver.cs
> +        [DllImport("nlopt", CallingConvention = CallingConvention.Cdecl)]
Use tabs.

2021-08-19 12:25 UTC, JeremyBois commented on NLoptNet/NLoptSolver.cs
> +                    IntPtr p_x,
I suppose the .Net approach with `In` and `Out` is only there to remove boilerplate code required with mono (not an expert). However currently the mono approach required allocation of a new bloc of memory each time a wrapped function is called. Maybe the .Net way performs better memory management but again not an expert. 

I would tend to say that is better to keep the .Net approach when possible for the explained reasons.

2021-08-19 12:35 UTC, JeremyBois commented
> 
> 
> Do we need to upgrade the deployment frameworks to include Mono somehow?

I am not sure to understand what you means. If you want to be able to run tests with mono I cannot help because my understanding of Visual Studio is very limited (not using it at all ...). There is an installer for mono on Windows [here](https://www.mono-project.com/download/stable/)

2021-08-24 18:04 UTC, merged