Add support for .NET Framework 4.7 and higher
BrannonKing/NLoptNet pull request #23
Opened 2021-12-14 16:25 UTC by rogerlord

This PR resolves #20 and adds support for .NET Framework 4.7 and higher, as well as retaining support for the more modern .NET Core and .NET 5.0/6.0 frameworks, by delivering a .NET Standard 2.0 DLL package (as was present before).

Downstream users should no longer have the need to use LoadLibrary to load the native nlopt DLL in their applications, this should all be done by the NLoptNet package going forward.

2021-12-14 16:29 UTC, rogerlord commented on NLoptNet.NuGet.Tests/SolverTests.cs
> +	public class SolverTests
These are exactly the same tests as in NLoptNet.Tests - save for the removal of the LoadLibrary call, which is no longer necessary.

2021-12-14 16:30 UTC, rogerlord commented on NLoptNet/NLoptNet.csproj
> +    <TargetFrameworks>netstandard2.0;net47</TargetFrameworks>
This will multi-target and provide .NET Standard 2.0 and .NET 4.7 DLLs going forward

2021-12-14 16:32 UTC, rogerlord commented on NLoptNet/NLoptNet.csproj
> +    <None Include="runtimes\win-x64\native\nlopt.dll" Pack="true" PackagePath="lib/net47/nlopt_x64.dll">
This should be the same list as before, save:
* Update has to be replaced by Include - unclear why this is the case, but otherwise it does not work when multi-targetting
* For the .NET 4.7 scenario, the package path needs to be lib/net47 - no subfolders can be used, so both the 32 bit and 64 bit are put in the same folder, with _x32 and _x64 added as a suffix. LoadLibrary is used to load the right DLL depending on the architecture.

2021-12-14 16:41 UTC, rogerlord commented on NLoptNet/NLoptSolver.cs
> +	public partial class NLoptSolver : IDisposable
The class has been made partial - and is spread over three files:
* NLoptSolver.cs - any functions common among .NET Standard and .NET Framework targets
* NLoptSolver_netstandard.cs - any functions specific to target .NET Standard - largely the code that was there before
* NLoptSolver_netfx.cs - any functions specific to target .NET Framework

2021-12-14 16:42 UTC, rogerlord commented on NLoptNet/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("1.4.0.0")]
I've bumped the version to 1.4

2021-12-14 16:44 UTC, rogerlord commented on NLoptNet/NLoptSolver_netfx.cs
> +		private static void nlopt_version(out int major, out int minor, out int bugfix)
Each function decides based on whether we are running on a 32-bit or 64-bit system which one to call. 32-bit functionality will be avaiable in nlopt_x32.dll and nlopt_x64.dll.

2021-12-14 16:49 UTC, rogerlord commented on .github/workflows/dotnet.yml
> +    runs-on: windows-latest
This builds and runs tests in a Windows container

2021-12-14 16:50 UTC, rogerlord commented on .github/workflows/dotnet.yml
> +      run: dotnet build --no-restore -c Release
Builds all frameworks in Release mode

2021-12-14 16:50 UTC, rogerlord commented on .github/workflows/dotnet.yml
> +      run: dotnet pack --no-build -c Release /p:PackageVersion=0.0.0-local
Tests the packaging - and builds a local package (used in NLoptNet.NuGet.Tests).

2021-12-14 16:50 UTC, rogerlord commented on .github/workflows/dotnet.yml
> +      run: dotnet test --no-build -c Release
Runs the already existing unit tests

2021-12-14 16:51 UTC, rogerlord commented on .github/workflows/dotnet.yml
> +        dotnet nuget add source ${{ github.workspace }}/pack -n="LocalNLopt"
Runs the tests using the local package, in all frameworks and AnyCPU / x64 platforms.

2021-12-14 17:13 UTC, BrannonKing requested changes

2021-12-14 17:13 UTC, BrannonKing commented on NLoptNet/NLoptNet.csproj
> +    <SignAssembly>false</SignAssembly>
We probably need to keep the strong signing.

2021-12-14 17:27 UTC, rogerlord commented on NLoptNet/NLoptNet.csproj
> +    <SignAssembly>false</SignAssembly>
Fair point - I got the following error locally when trying to build it:

`PFX signing not supported on .NET Core`

so I disabled it, but there are ways around that, see e.g. [here](https://stackoverflow.com/questions/51105698/how-to-work-around-the-pfx-signing-not-supported-error-when-publishing-net-core). To get it to work on the pipeline we'd need to find a way of passing your password as a secret, in order not to expose it.

Alternatively, we can enable it in the main code but disable it on the fly in the build script. I'd prefer that as a quick fix at the moment, what do you think?

2021-12-14 18:40 UTC, rogerlord commented on NLoptNet/NLoptNet.csproj
> +    <SignAssembly>false</SignAssembly>
Added it back and applied the second idea for now. Let me know.

2021-12-15 07:51 UTC, rogerlord commented on NLoptNet/NLoptNet.csproj
> +    <SignAssembly>false</SignAssembly>
FYI - if you'd want to get the first step to work (i.e. signing it as part of the build), [here](https://www.bakx.ca/articles/2020/code-signing-net-assemblies-with-github-actions/) are some pointers for someone facing a similar situation.

2021-12-15 14:48 UTC, BrannonKing commented on NLoptNet/NLoptNet.csproj
> +    <None Include="runtimes\win-x64\native\nlopt.dll" Pack="true" PackagePath="lib/net47/nlopt_x64.dll">
Is it worth supporting .NET Framework 4.8?

2021-12-15 15:52 UTC, merged