Address .NET Framework warnings for consuming projects
BrannonKing/NLoptNet pull request #27
Opened 2022-03-27 16:08 UTC by rogerlord

Resolves #25 

In version 1.4.0.0 a slightly different structure was chosen for the project, by multi-targeting for both .NET Framework 4.7 as well as for .NET Standard. Although the new SDK project format allows for multi-targeting, it does not seem to cater well for including native assemblies in NuGet packages. The result was that consuming projects get warnings about potential BadImageExceptions.

This PR addresses that by adding a .nuspec file which generates the NuGet package. Two warnings are still generated when creating the NuGet package, but consumers should not have any more issues.

2022-03-27 19:32 UTC, rogerlord commented on NLoptNet/NLoptNet.csproj
> -    <None Include="runtimes\win-x86\native\nlopt.dll" Pack="true" PackagePath="lib/net47/nlopt_x32.dll">
These lines were causing the original warnings

2022-03-27 19:34 UTC, rogerlord commented on NLoptNet/NLoptNet.csproj
> +  <ItemGroup Condition="'$(TargetFramework)'=='net47'">
When building NLoptNet, and targeting .NET 4.7, this copies the relevant nlopt DLLs to the bin folder

2022-03-27 19:34 UTC, rogerlord commented on NLoptNet/build/NLoptnet.targets
> +<Project>
Runs in all consuming projects, and copies the native DLLs to the output folder when targeting .NET 4.7, 4.7.1, 4.7.2 or 4.8.

2022-03-27 19:35 UTC, rogerlord commented on NLoptNet/nloptnet.nuspec
> +﻿<?xml version="1.0" encoding="utf-8"?>
.nuspec file that works around the issues with multi-targeting experienced with the SDK csproj file

2022-03-27 19:36 UTC, rogerlord commented on .github/workflows/dotnet.windows.yml
> -          2.1.x
Where possible have removed the dependency on old frameworks in the Actions workflows

2022-03-28 10:19 UTC, rogerlord commented on .github/workflows/dotnet.linux.yml
> +        sed -i 's/net47;net48;//g' ./NLoptNet.NuGet.Tests/NLoptNet.NuGet.Tests.csproj
Not using replace-in-file, but just directly using sed removes the need for installing .NET Core 2.1.x, which gets rid of a warning in the GitHub Action for Linux.

2022-03-28 11:22 UTC, BrannonKing approved these changes
I think the changes look fine overall.

2022-03-28 11:30 UTC, BrannonKing requested changes
The AssemblyInfo.cs file needs to have version numbers updated. I'm not sure how that relates to the GenerateAssemblyInfo flag. Also, please squash the commits. 33 is too many.

2022-03-28 11:32 UTC, rogerlord commented on NLoptNet/NLoptNet.csproj
> +	<TargetFrameworks>netstandard2.0;net47</TargetFrameworks>
Had noticed in the review of the PR, but I don't see it in my editor.

2022-03-28 11:36 UTC, rogerlord commented
Hi @BrannonKing - I will remove the AssemblyVersion from AssemblyInfo.cs, I don't think it's needed there as it's already set elsewhere.

As for the squash - that's something you should be able to do when merging:

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

2022-03-28 11:50 UTC, rogerlord commented
Done - removing the version in AssemblyInfo will need changing of the build, so I've just upgraded the version for now.
Tabs / spaces is also cleaned up now, in the .csproj file.

As mentioned, when you merge, if the repo is configured for that, you can squash the entire PR into one commit if you prefer to do so.

2022-03-28 12:11 UTC, rogerlord commented on NLoptNet/NLoptNet.csproj
> +	<TargetFrameworks>netstandard2.0;net47</TargetFrameworks>
Has been fixed

2022-03-31 14:38 UTC, merged